// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Accaunts struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Enteries struct {
	ID         int64 `json:"id"`
	AccauntsID int64 `json:"accaunts_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfers struct {
	ID             int64 `json:"id"`
	FromAccauntsID int64 `json:"from_accaunts_id"`
	ToAccauntsID   int64 `json:"to_accaunts_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
